// <auto-generated />
namespace RSGymPT_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class M02PersonalTrainerClass_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M02PersonalTrainerClass_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "202304050913276_M02PersonalTrainerClass_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
